name: Jest
on: push
env:
    HASH_SECRET: ${{ secrets.HASH_SECRET }}
    JWT_TOKEN_SECRET: ${{ secrets.JWT_TOKEN_SECRET }}
    TZ: 'Europe/Paris'
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '18'

            # Speed up subsequent runs with caching
            - name: Cache node modules
              uses: actions/cache@v3
              env:
                  cache-name: cache-node-modules
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            # Install required deps for action
            - name: Install Dependencies
              run: npm install

            - name: Install client dependencies
              run: cd src/client && npm install

            # Finally, run our tests
            - name: Run the back-end tests
              run: npm run test:back

            - name: Run the front-end tests
              run: npm run test:front
